spring:
  main:
    banner-mode: log
    web-application-type: reactive

  ai:
    mcp:
      server:
        stdio: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
